domain_path: /home/min/robo-digger-project/soc/platform_jy/export/platform_jy/sw/standalone_microblaze_riscv_0
app_src_dir: /home/user11/tools/Vitis/2024.2/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
lang: c
