domain_path: /home/min/robo-digger-project/soc/platform_digger/export/platform_digger/sw/standalone_microblaze_riscv_0
app_src_dir: /tools/Xilinx/Vitis/2024.2/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
lang: c
