#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral MICROBLAZE_RISCV_0_AXI_INTC */
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_BASEADDR 0x41200000
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_HIGHADDR 0x4120ffff
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_KIND_OF_INTR 0x3
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_IS_FAST 0x1
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_IVAR_RST_VAL 0x10
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_NUM_INTR_INPUTS 0x2
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_ADDR_WIDTH 0x20
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_OPTIONS 0x0
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_INTCTYPE 0x0
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_HANDLER_TABLE 0x0
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_NUM_SW_INTR 0x0

/* Canonical definitions for peripheral MICROBLAZE_RISCV_0_AXI_INTC */
#define XPAR_XINTC_0_BASEADDR 0x41200000
#define XPAR_XINTC_0_HIGHADDR 0x4120ffff
#define XPAR_XINTC_0_HANDLER_TABLE 0x0
#define XPAR_XINTC_0_ADDR_WIDTH 0x20
#define XPAR_XINTC_0_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_XINTC_0_IS_FAST 0x1
#define XPAR_XINTC_0_IVAR_RST_VAL 0x10
#define XPAR_XINTC_0_INTCTYPE 0x0
#define XPAR_XINTC_0_KIND_OF_INTR 0x3
#define XPAR_XINTC_0_NUM_INTR_INPUTS 0x2
#define XPAR_XINTC_0_NUM_SW_INTR 0x0
#define XPAR_XINTC_0_OPTIONS 0x0

#define XPAR_XUARTLITE_NUM_INSTANCES 2

/* Definitions for peripheral AXI_HC05_UART */
#define XPAR_AXI_HC05_UART_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_AXI_HC05_UART_BASEADDR 0x40610000
#define XPAR_AXI_HC05_UART_HIGHADDR 0x4061ffff
#define XPAR_AXI_HC05_UART_BAUDRATE 0x9600
#define XPAR_AXI_HC05_UART_USE_PARITY 0x0
#define XPAR_AXI_HC05_UART_ODD_PARITY 0x0
#define XPAR_AXI_HC05_UART_DATA_BITS 0x8
#define XPAR_AXI_HC05_UART_INTERRUPTS 0x0
#define XPAR_FABRIC_AXI_HC05_UART_INTR 0
#define XPAR_AXI_HC05_UART_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral AXI_HC05_UART */
#define XPAR_XUARTLITE_0_BASEADDR 0x40610000
#define XPAR_FABRIC_XUARTLITE_0_INTR 0
#define XPAR_XUARTLITE_0_HIGHADDR 0x4061ffff
#define XPAR_XUARTLITE_0_BAUDRATE 0x9600
#define XPAR_XUARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_XUARTLITE_0_DATA_BITS 0x8
#define XPAR_XUARTLITE_0_INTERRUPTS 0x0
#define XPAR_XUARTLITE_0_INTERRUPT_PARENT 0x41200001
#define XPAR_XUARTLITE_0_ODD_PARITY 0x0
#define XPAR_XUARTLITE_0_USE_PARITY 0x0

/* Definitions for peripheral AXI_USB_UART */
#define XPAR_AXI_USB_UART_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_AXI_USB_UART_BASEADDR 0x40600000
#define XPAR_AXI_USB_UART_HIGHADDR 0x4060ffff
#define XPAR_AXI_USB_UART_BAUDRATE 0x9600
#define XPAR_AXI_USB_UART_USE_PARITY 0x0
#define XPAR_AXI_USB_UART_ODD_PARITY 0x0
#define XPAR_AXI_USB_UART_DATA_BITS 0x8

/* Canonical definitions for peripheral AXI_USB_UART */
#define XPAR_XUARTLITE_1_BASEADDR 0x40600000
#define XPAR_XUARTLITE_1_HIGHADDR 0x4060ffff
#define XPAR_XUARTLITE_1_BAUDRATE 0x9600
#define XPAR_XUARTLITE_1_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_XUARTLITE_1_DATA_BITS 0x8
#define XPAR_XUARTLITE_1_ODD_PARITY 0x0
#define XPAR_XUARTLITE_1_USE_PARITY 0x0

/* Definitions for peripheral MYIP_HANDLE_0 */
#define XPAR_MYIP_HANDLE_0_BASEADDR 0x44aa0000
#define XPAR_MYIP_HANDLE_0_HIGHADDR 0x44aaffff

/* Canonical definitions for peripheral MYIP_HANDLE_0 */
#define XPAR_MYIP_HANDLE_0_BASEADDR 0x44aa0000
#define XPAR_MYIP_HANDLE_0_HIGHADDR 0x44aaffff

/* Definitions for peripheral MYIP_PWM_BLADE */
#define XPAR_MYIP_PWM_BLADE_BASEADDR 0x44a60000
#define XPAR_MYIP_PWM_BLADE_HIGHADDR 0x44a6ffff

/* Canonical definitions for peripheral MYIP_PWM_BLADE */
#define XPAR_MYIP_PWM_0_BASEADDR 0x44a60000
#define XPAR_MYIP_PWM_0_HIGHADDR 0x44a6ffff

/* Definitions for peripheral MYIP_PWM_LEFT_WHEEL */
#define XPAR_MYIP_PWM_LEFT_WHEEL_BASEADDR 0x44a40000
#define XPAR_MYIP_PWM_LEFT_WHEEL_HIGHADDR 0x44a4ffff

/* Canonical definitions for peripheral MYIP_PWM_LEFT_WHEEL */
#define XPAR_MYIP_PWM_1_BASEADDR 0x44a40000
#define XPAR_MYIP_PWM_1_HIGHADDR 0x44a4ffff

/* Definitions for peripheral MYIP_PWM_RIGHT_WHEEL */
#define XPAR_MYIP_PWM_RIGHT_WHEEL_BASEADDR 0x44a70000
#define XPAR_MYIP_PWM_RIGHT_WHEEL_HIGHADDR 0x44a7ffff

/* Canonical definitions for peripheral MYIP_PWM_RIGHT_WHEEL */
#define XPAR_MYIP_PWM_2_BASEADDR 0x44a70000
#define XPAR_MYIP_PWM_2_HIGHADDR 0x44a7ffff

/* Definitions for peripheral MYIP_PWM_X1 */
#define XPAR_MYIP_PWM_X1_BASEADDR 0x44a00000
#define XPAR_MYIP_PWM_X1_HIGHADDR 0x44a0ffff

/* Canonical definitions for peripheral MYIP_PWM_X1 */
#define XPAR_MYIP_PWM_3_BASEADDR 0x44a00000
#define XPAR_MYIP_PWM_3_HIGHADDR 0x44a0ffff

/* Definitions for peripheral MYIP_PWM_X2 */
#define XPAR_MYIP_PWM_X2_BASEADDR 0x44a20000
#define XPAR_MYIP_PWM_X2_HIGHADDR 0x44a2ffff

/* Canonical definitions for peripheral MYIP_PWM_X2 */
#define XPAR_MYIP_PWM_4_BASEADDR 0x44a20000
#define XPAR_MYIP_PWM_4_HIGHADDR 0x44a2ffff

/* Definitions for peripheral MYIP_PWM_Y1 */
#define XPAR_MYIP_PWM_Y1_BASEADDR 0x44a10000
#define XPAR_MYIP_PWM_Y1_HIGHADDR 0x44a1ffff

/* Canonical definitions for peripheral MYIP_PWM_Y1 */
#define XPAR_MYIP_PWM_5_BASEADDR 0x44a10000
#define XPAR_MYIP_PWM_5_HIGHADDR 0x44a1ffff

/* Definitions for peripheral MYIP_PWM_Y2 */
#define XPAR_MYIP_PWM_Y2_BASEADDR 0x44a30000
#define XPAR_MYIP_PWM_Y2_HIGHADDR 0x44a3ffff

/* Canonical definitions for peripheral MYIP_PWM_Y2 */
#define XPAR_MYIP_PWM_6_BASEADDR 0x44a30000
#define XPAR_MYIP_PWM_6_HIGHADDR 0x44a3ffff

/*  BOARD definition */
#define XPS_BOARD_BASYS3

#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0x1ffff

/*  CPU parameters definition */
#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000
#define XPAR_MICROBLAZE_RISCV_USE_DCACHE 0
#define XPAR_MICROBLAZE_RISCV_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_DCACHE_BYTE_SIZE 4096
#define XPAR_MICROBLAZE_RISCV_USE_ICACHE 0
#define XPAR_MICROBLAZE_RISCV_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_ICACHE_BYTE_SIZE 4096
#define XPAR_MICROBLAZE_RISCV_USE_FPU 0
#define XPAR_MICROBLAZE_RISCV_USE_MMU 0
#define XPAR_MICROBLAZE_RISCV_USE_SLEEP 0
#define XPAR_MICROBLAZE_RISCV_FAULT_TOLERANT 0
#define XPAR_MICROBLAZE_RISCV_D_LMB 1
#define XPAR_MICROBLAZE_RISCV_USE_BRANCH_TARGET_CACHE 0
#define XPAR_MICROBLAZE_RISCV_BRANCH_TARGET_CACHE_SIZE 0

/* Device ID */
#define XPAR_DEVICE_ID "7a35t"

#endif  /* end of protection macro */